<?php

return [
    'recepcion' => [
        'label' => 'Recepción',
        'description' => 'Atención inicial, agenda y seguimiento básico.',
        'permissions' => [
            'dashboard.view',
            'agenda.view',
            'pacientes.view',
            'pacientes.flujo.view',
            'pacientes.edit',
            'derivaciones.view',
            'solicitudes.view',
            'solicitudes.turnero',
            'examenes.view',
        ],
    ],
    'coordinacion_quirurgica' => [
        'label' => 'Coordinación quirúrgica',
        'description' => 'Operación de solicitudes, turnero y protocolos.',
        'permissions' => [
            'dashboard.view',
            'solicitudes.view',
            'solicitudes.update',
            'solicitudes.turnero',
            'cirugias.view',
            'cirugias.create',
            'cirugias.edit',
            'cirugias.dashboard.view',
            'ipl.view',
            'protocolos.templates.view',
            'reportes.view',
            'reportes.export',
        ],
    ],
    'imagenes_examenes' => [
        'label' => 'Imágenes y exámenes',
        'description' => 'Operación del kanban de exámenes y CRM asociado.',
        'permissions' => [
            'dashboard.view',
            'examenes.view',
            'examenes.checklist.override',
            'reportes.view',
            'reportes.export',
            'crm.view',
        ],
    ],
    'facturacion' => [
        'label' => 'Facturación',
        'description' => 'Informes, no facturados y exportaciones financieras.',
        'permissions' => [
            'dashboard.view',
            'reportes.view',
            'reportes.export',
            'solicitudes.view',
            'examenes.view',
        ],
    ],
    'crm_captacion' => [
        'label' => 'CRM y captación',
        'description' => 'Marketing, leads, tareas y tickets.',
        'permissions' => [
            'dashboard.view',
            'crm.view',
            'crm.leads.manage',
            'crm.projects.manage',
            'crm.tasks.manage',
            'crm.tickets.manage',
            'whatsapp.chat.view',
            'whatsapp.chat.send',
        ],
    ],
    'administracion_ti' => [
        'label' => 'Administración y TI',
        'description' => 'Gestión administrativa y configuración del sistema.',
        'permissions' => [
            'administrativo',
            'admin.usuarios.view',
            'admin.usuarios.manage',
            'admin.roles.view',
            'admin.roles.manage',
            'settings.view',
            'settings.manage',
            'codes.view',
            'codes.manage',
            'whatsapp.manage',
            'superuser',
        ],
    ],
];
