<?php

return [
    'defaults' => [
        'legacy_base_url' => getenv('SMOKE_LEGACY_BASE') ?: 'http://127.0.0.1:8080',
        'v2_base_url' => getenv('SMOKE_V2_BASE') ?: 'http://127.0.0.1:8081',
        'timeout_seconds' => 20,
    ],
    'fixtures' => [
        'HC_NUMBER' => getenv('SMOKE_HC_NUMBER') ?: 'HC-TEST-001',
        'SOLICITUD_ID' => getenv('SMOKE_SOLICITUD_ID') ?: '',
        'BILLING_FORM_ID' => getenv('SMOKE_BILLING_FORM_ID') ?: '',
        'BILLING_HC_NUMBER' => getenv('SMOKE_BILLING_HC_NUMBER') ?: '',
        'REPORT_FORM_ID' => getenv('SMOKE_REPORT_FORM_ID') ?: '',
        'REPORT_HC_NUMBER' => getenv('SMOKE_REPORT_HC_NUMBER') ?: '',
        'REPORT_DIAS_DESCANSO' => getenv('SMOKE_REPORT_DIAS_DESCANSO') ?: '5',
    ],
    'modules' => [
        'dashboard' => [
            [
                'id' => 'dashboard_ui',
                'method' => 'GET',
                'legacy_path' => '/dashboard',
                'v2_path' => '/v2/dashboard',
                'expect_status' => 401,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'notes' => 'Guest mode sends Accept: application/json, so v2 dashboard UI returns JSON 401.',
                'notes_auth' => 'Authenticated mode validates that /v2/dashboard renders HTML (status 200).',
            ],
            [
                'id' => 'dashboard_summary',
                'method' => 'GET',
                'legacy_path' => '/dashboard',
                'v2_path' => '/v2/dashboard/summary',
                'expect_status' => 401,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [
                    'data.patients_total',
                    'data.users_total',
                    'data.protocols_total',
                    'data.total_cirugias_periodo',
                    'data.procedimientos_dia.fechas',
                    'data.procedimientos_dia.totales',
                    'data.top_procedimientos.membretes',
                    'data.top_procedimientos.totales',
                    'data.revision_estados.incompletos',
                    'data.revision_estados.revisados',
                    'data.revision_estados.no_revisados',
                    'data.solicitudes_funnel.etapas',
                    'data.solicitudes_funnel.totales',
                    'data.crm_backlog.pendientes',
                    'meta.date_range.start',
                    'meta.date_range.end',
                    'meta.date_range.label',
                ],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'notes' => 'Guest mode validates auth requirement in v2 dashboard summary.',
                'notes_auth' => 'Authenticated mode validates dashboard v2 payload shape. Legacy status parity is skipped when UI cutover redirects /dashboard -> /v2/dashboard.',
            ],
        ],
        'dashboard_cutover' => [
            [
                'id' => 'dashboard_ui_cutover_redirect',
                'method' => 'GET',
                'legacy_path' => '/dashboard',
                'v2_path' => '/dashboard',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/dashboard',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/dashboard',
                ],
                'notes' => 'Use this only when DASHBOARD_V2_UI_ENABLED=1 to verify /dashboard cutover redirect to /v2/dashboard.',
                'notes_auth' => 'Authenticated mode also expects /dashboard redirecting to /v2/dashboard when UI cutover is enabled.',
            ],
        ],
        'reporting_cutover' => [
            [
                'id' => 'reporting_legacy_protocolo_redirect',
                'method' => 'GET',
                'legacy_path' => '/reports/protocolo/pdf?form_id=1&hc_number=1',
                'v2_path' => '/reports/protocolo/pdf?form_id=1&hc_number=1',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/reports/protocolo/pdf?form_id=1&hc_number=1',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/reports/protocolo/pdf?form_id=1&hc_number=1',
                ],
                'notes' => 'Legacy protocolo endpoint must redirect to v2 endpoint.',
            ],
            [
                'id' => 'reporting_legacy_cobertura_redirect',
                'method' => 'GET',
                'legacy_path' => '/reports/cobertura/pdf?form_id=1&hc_number=1',
                'v2_path' => '/reports/cobertura/pdf?form_id=1&hc_number=1',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/reports/cobertura/pdf?form_id=1&hc_number=1',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/reports/cobertura/pdf?form_id=1&hc_number=1',
                ],
                'notes' => 'Legacy cobertura endpoint must redirect to v2 endpoint.',
            ],
            [
                'id' => 'reporting_legacy_cobertura_queue_enqueue',
                'method' => 'GET',
                'legacy_path' => '/reports/cobertura/pdf-queue?form_id=1&hc_number=1&variant=template',
                'v2_path' => '/reports/cobertura/pdf-queue?form_id=1&hc_number=1&variant=template',
                'expect_status' => 202,
                'expect_v2_status' => 202,
                'expect_v2_status_auth' => 202,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['ok', 'strategy', 'job_id', 'status_url'],
                'required_json_paths_auth' => ['ok', 'strategy', 'job_id', 'status_url'],
                'notes' => 'Queue shim must return synthetic job metadata without legacy PDF generation.',
            ],
            [
                'id' => 'reporting_legacy_cobertura_queue_status',
                'method' => 'GET',
                'legacy_path' => '/reports/cobertura/pdf-queue/status?id=v2-smoke&target=%2Fv2%2Freports%2Fcobertura%2Fpdf%3Fform_id%3D1%26hc_number%3D1%26variant%3Dtemplate',
                'v2_path' => '/reports/cobertura/pdf-queue/status?id=v2-smoke&target=%2Fv2%2Freports%2Fcobertura%2Fpdf%3Fform_id%3D1%26hc_number%3D1%26variant%3Dtemplate',
                'expect_status' => 200,
                'expect_v2_status' => 200,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['ok', 'job.id', 'job.status', 'job.strategy', 'job.download_url'],
                'required_json_paths_auth' => ['ok', 'job.id', 'job.status', 'job.strategy', 'job.download_url'],
                'notes' => 'Queue status shim must resolve to completed job with v2 download URL.',
            ],
            [
                'id' => 'reporting_legacy_consulta_redirect',
                'method' => 'GET',
                'legacy_path' => '/reports/consulta/pdf?form_id=1&hc_number=1',
                'v2_path' => '/reports/consulta/pdf?form_id=1&hc_number=1',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/reports/consulta/pdf?form_id=1&hc_number=1',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/reports/consulta/pdf?form_id=1&hc_number=1',
                ],
                'notes' => 'Legacy consulta endpoint must redirect to v2 endpoint.',
            ],
            [
                'id' => 'reporting_legacy_descanso_redirect',
                'method' => 'GET',
                'legacy_path' => '/reports/cirugias/descanso/pdf?form_id=1&hc_number=1&dias_descanso=5',
                'v2_path' => '/reports/cirugias/descanso/pdf?form_id=1&hc_number=1&dias_descanso=5',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/reports/cirugias/descanso/pdf?form_id=1&hc_number=1&dias_descanso=5',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/reports/cirugias/descanso/pdf?form_id=1&hc_number=1&dias_descanso=5',
                ],
                'notes' => 'Legacy descanso endpoint must redirect to v2 endpoint.',
            ],
            [
                'id' => 'reporting_legacy_012a_redirect',
                'method' => 'GET',
                'legacy_path' => '/examenes/cobertura-012a/pdf?form_id=1&hc_number=1',
                'v2_path' => '/examenes/cobertura-012a/pdf?form_id=1&hc_number=1',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/reports/imagenes/012a/pdf?form_id=1&hc_number=1',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/reports/imagenes/012a/pdf?form_id=1&hc_number=1',
                ],
                'notes' => 'Legacy cobertura 012A endpoint must redirect to v2 endpoint.',
            ],
            [
                'id' => 'reporting_legacy_012b_redirect',
                'method' => 'GET',
                'legacy_path' => '/imagenes/informes/012b/pdf?form_id=1&hc_number=1',
                'v2_path' => '/imagenes/informes/012b/pdf?form_id=1&hc_number=1',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/reports/imagenes/012b/pdf?form_id=1&hc_number=1',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/reports/imagenes/012b/pdf?form_id=1&hc_number=1',
                ],
                'notes' => 'Legacy informe 012B endpoint must redirect to v2 endpoint.',
            ],
            [
                'id' => 'reporting_legacy_012b_paquete_redirect',
                'method' => 'GET',
                'legacy_path' => '/imagenes/informes/012b/paquete?form_id=1&hc_number=1',
                'v2_path' => '/imagenes/informes/012b/paquete?form_id=1&hc_number=1',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/reports/imagenes/012b/paquete?form_id=1&hc_number=1',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/reports/imagenes/012b/paquete?form_id=1&hc_number=1',
                ],
                'notes' => 'Legacy paquete 012B endpoint must redirect to v2 endpoint.',
            ],
            [
                'id' => 'reporting_legacy_012b_paquete_seleccion_redirect',
                'method' => 'POST',
                'legacy_path' => '/imagenes/informes/012b/paquete/seleccion',
                'v2_path' => '/imagenes/informes/012b/paquete/seleccion',
                'body' => [
                    'items' => [
                        ['form_id' => '1', 'hc_number' => '1'],
                    ],
                ],
                'expect_status' => 307,
                'expect_v2_status' => 307,
                'expect_v2_status_auth' => 307,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/reports/imagenes/012b/paquete/seleccion',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/reports/imagenes/012b/paquete/seleccion',
                ],
                'notes' => 'Legacy paquete seleccion endpoint must preserve POST method and redirect to v2 endpoint.',
            ],
            [
                'id' => 'reporting_v2_protocolo_pdf',
                'method' => 'GET',
                'legacy_path' => '/v2/reports/protocolo/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'v2_path' => '/v2/reports/protocolo/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'requires_reporting_fixture' => true,
                'expect_status' => 401,
                'expect_v2_status' => 401,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'required_v2_headers_auth' => ['content-type', 'x-request-id'],
                'assert_v2_header_contains_auth' => [
                    'content-type' => 'application/pdf',
                ],
                'notes' => 'Guest mode validates auth requirement for v2 protocolo PDF.',
                'notes_auth' => 'Authenticated mode validates protocolo PDF generation in v2.',
            ],
            [
                'id' => 'reporting_v2_cobertura_pdf',
                'method' => 'GET',
                'legacy_path' => '/v2/reports/cobertura/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'v2_path' => '/v2/reports/cobertura/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'requires_reporting_fixture' => true,
                'expect_status' => 401,
                'expect_v2_status' => 401,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'required_v2_headers_auth' => ['content-type', 'x-request-id'],
                'assert_v2_header_contains_auth' => [
                    'content-type' => 'application/pdf',
                ],
                'notes' => 'Guest mode validates auth requirement for v2 cobertura PDF.',
                'notes_auth' => 'Authenticated mode validates cobertura PDF generation in v2.',
            ],
            [
                'id' => 'reporting_v2_consulta_pdf',
                'method' => 'GET',
                'legacy_path' => '/v2/reports/consulta/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'v2_path' => '/v2/reports/consulta/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'requires_reporting_fixture' => true,
                'expect_status' => 401,
                'expect_v2_status' => 401,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'required_v2_headers_auth' => ['content-type', 'x-request-id'],
                'assert_v2_header_contains_auth' => [
                    'content-type' => 'application/pdf',
                ],
                'notes' => 'Guest mode validates auth requirement for v2 consulta PDF.',
                'notes_auth' => 'Authenticated mode validates consulta PDF generation in v2.',
            ],
            [
                'id' => 'reporting_v2_descanso_pdf',
                'method' => 'GET',
                'legacy_path' => '/v2/reports/cirugias/descanso/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}&dias_descanso={REPORT_DIAS_DESCANSO}',
                'v2_path' => '/v2/reports/cirugias/descanso/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}&dias_descanso={REPORT_DIAS_DESCANSO}',
                'requires_reporting_fixture' => true,
                'expect_status' => 401,
                'expect_v2_status' => 401,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'required_v2_headers_auth' => ['content-type', 'x-request-id'],
                'assert_v2_header_contains_auth' => [
                    'content-type' => 'application/pdf',
                ],
                'notes' => 'Guest mode validates auth requirement for v2 descanso PDF.',
                'notes_auth' => 'Authenticated mode validates descanso PDF generation in v2.',
            ],
            [
                'id' => 'reporting_v2_012a_pdf',
                'method' => 'GET',
                'legacy_path' => '/v2/reports/imagenes/012a/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'v2_path' => '/v2/reports/imagenes/012a/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'requires_reporting_fixture' => true,
                'expect_status' => 401,
                'expect_v2_status' => 401,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'required_v2_headers_auth' => ['content-type', 'x-request-id'],
                'assert_v2_header_contains_auth' => [
                    'content-type' => 'application/pdf',
                ],
                'notes' => 'Guest mode validates auth requirement for v2 012A PDF.',
                'notes_auth' => 'Authenticated mode validates 012A PDF generation in v2.',
            ],
            [
                'id' => 'reporting_v2_012b_pdf',
                'method' => 'GET',
                'legacy_path' => '/v2/reports/imagenes/012b/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'v2_path' => '/v2/reports/imagenes/012b/pdf?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'requires_reporting_fixture' => true,
                'expect_status' => 401,
                'expect_v2_status' => 401,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'required_v2_headers_auth' => ['content-type', 'x-request-id'],
                'assert_v2_header_contains_auth' => [
                    'content-type' => 'application/pdf',
                ],
                'notes' => 'Guest mode validates auth requirement for v2 012B PDF.',
                'notes_auth' => 'Authenticated mode validates 012B PDF generation in v2.',
            ],
            [
                'id' => 'reporting_v2_012b_paquete_pdf',
                'method' => 'GET',
                'legacy_path' => '/v2/reports/imagenes/012b/paquete?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'v2_path' => '/v2/reports/imagenes/012b/paquete?form_id={REPORT_FORM_ID}&hc_number={REPORT_HC_NUMBER}',
                'requires_reporting_fixture' => true,
                'expect_status' => 401,
                'expect_v2_status' => 401,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'required_v2_headers_auth' => ['content-type', 'x-request-id'],
                'assert_v2_header_contains_auth' => [
                    'content-type' => 'application/pdf',
                ],
                'notes' => 'Guest mode validates auth requirement for v2 012B package PDF.',
                'notes_auth' => 'Authenticated mode validates 012B package PDF generation in v2.',
            ],
            [
                'id' => 'reporting_v2_012b_paquete_seleccion_pdf',
                'method' => 'POST',
                'legacy_path' => '/v2/reports/imagenes/012b/paquete/seleccion',
                'v2_path' => '/v2/reports/imagenes/012b/paquete/seleccion',
                'body' => [
                    'items' => [
                        ['form_id' => '{REPORT_FORM_ID}', 'hc_number' => '{REPORT_HC_NUMBER}'],
                    ],
                ],
                'requires_reporting_fixture' => true,
                'expect_status' => 401,
                'expect_v2_status' => 401,
                'expect_v2_status_auth' => 200,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'required_v2_headers_auth' => ['content-type', 'x-request-id'],
                'assert_v2_header_contains_auth' => [
                    'content-type' => 'application/pdf',
                ],
                'notes' => 'Guest mode validates auth requirement for v2 012B package selection PDF.',
                'notes_auth' => 'Authenticated mode validates 012B package selection PDF generation in v2.',
            ],
        ],
        'solicitudes_cutover' => [
            [
                'id' => 'solicitudes_ui_cutover_redirect',
                'method' => 'GET',
                'legacy_path' => '/solicitudes',
                'v2_path' => '/solicitudes',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/solicitudes',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/solicitudes',
                ],
                'notes' => 'Use this only when SOLICITUDES_V2_UI_ENABLED=1 to verify /solicitudes redirect to /v2/solicitudes.',
                'notes_auth' => 'Authenticated mode also expects /solicitudes redirecting to /v2/solicitudes when UI cutover is enabled.',
            ],
            [
                'id' => 'solicitudes_dashboard_ui_cutover_redirect',
                'method' => 'GET',
                'legacy_path' => '/solicitudes/dashboard',
                'v2_path' => '/solicitudes/dashboard',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/solicitudes/dashboard',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/solicitudes/dashboard',
                ],
                'notes' => 'Use this only when SOLICITUDES_V2_UI_ENABLED=1 to verify /solicitudes/dashboard redirect to /v2/solicitudes/dashboard.',
                'notes_auth' => 'Authenticated mode also expects /solicitudes/dashboard redirecting to /v2/solicitudes/dashboard.',
            ],
            [
                'id' => 'solicitudes_turnero_ui_cutover_redirect',
                'method' => 'GET',
                'legacy_path' => '/solicitudes/turnero',
                'v2_path' => '/solicitudes/turnero',
                'expect_status' => 302,
                'expect_v2_status' => 302,
                'expect_v2_status_auth' => 302,
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'assert_v2_header_contains' => [
                    'location' => '/v2/solicitudes/turnero',
                ],
                'assert_v2_header_contains_auth' => [
                    'location' => '/v2/solicitudes/turnero',
                ],
                'notes' => 'Use this only when SOLICITUDES_V2_UI_ENABLED=1 to verify /solicitudes/turnero redirect to /v2/solicitudes/turnero.',
                'notes_auth' => 'Authenticated mode also expects /solicitudes/turnero redirecting to /v2/solicitudes/turnero.',
            ],
        ],
        'billing' => [
            [
                'id' => 'billing_no_facturados',
                'method' => 'GET',
                'legacy_path' => '/api/billing/no-facturados?start=0&length=10',
                'v2_path' => '/v2/api/billing/no-facturados?start=0&length=10',
                'expect_status' => 200,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 200,
                'required_json_paths' => ['recordsTotal', 'recordsFiltered', 'data', 'summary.total'],
                'compare_mode' => 'v2_only',
                'notes' => 'Legacy returns 302 when unauthenticated. Run with --cookie=PHPSESSID=... for full parity.',
            ],
            [
                'id' => 'billing_afiliaciones',
                'method' => 'GET',
                'legacy_path' => '/api/billing/afiliaciones',
                'v2_path' => '/v2/api/billing/afiliaciones',
                'expect_status' => 200,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 200,
                'required_json_paths' => ['0'],
                'compare_mode' => 'v2_only',
                'notes' => 'Legacy returns 302 when unauthenticated. Run with --cookie=PHPSESSID=... for full parity.',
            ],
            [
                'id' => 'billing_no_facturados_crear',
                'method' => 'POST',
                'legacy_path' => '/billing/no-facturados/crear',
                'v2_path' => '/v2/billing/no-facturados/crear',
                'body_format' => 'form',
                'body' => [
                    'form_id' => '{BILLING_FORM_ID}',
                    'hc_number' => '{BILLING_HC_NUMBER}',
                ],
                'requires_dynamic_fixture' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 302,
                'expect_v2_status_auth' => 302,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'status_only',
                'post_check_v2_auth' => [
                    'path' => '/v2/api/billing/no-facturados?start=0&length=10&busqueda={BILLING_FORM_ID}',
                    'method' => 'GET',
                    'expect_status' => 200,
                    'required_json_paths' => ['recordsFiltered', 'data'],
                    'assert_json_equals' => [
                        'recordsFiltered' => 0,
                    ],
                ],
                'notes' => 'Guest mode expects JSON 401 in v2 write endpoint.',
                'notes_auth' => 'Authenticated create expects redirect parity and validates the form is no longer pending in v2.',
            ],
            [
                'id' => 'billing_verificacion_derivacion',
                'method' => 'POST',
                'legacy_path' => '/api/billing/verificacion_derivacion.php',
                'v2_path' => '/v2/api/billing/verificacion_derivacion.php',
                'body_format' => 'form',
                'body' => [
                    'form_ids' => ['{BILLING_FORM_ID}'],
                ],
                'requires_dynamic_fixture' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 200,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['success', 'error'],
                'required_json_paths_auth' => ['success', 'existentes', 'nuevos'],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates v2 auth requirement on derivation verification.',
                'notes_auth' => 'Authenticated verification expects success payload with existentes/nuevos.',
            ],
            [
                'id' => 'billing_insertar_billing_main',
                'method' => 'POST',
                'legacy_path' => '/api/billing/insertar_billing_main.php',
                'v2_path' => '/v2/api/billing/insertar_billing_main.php',
                'body' => [
                    'procedimientos' => [
                        [
                            'form_id' => '{BILLING_FORM_ID}',
                            'hc_number' => '{BILLING_HC_NUMBER}',
                            'codigo' => '92012',
                            'detalle' => 'CONSULTA OFTALMOLOGICA DE CONTROL',
                            'procedimiento_proyectado' => 'SERVICIOS OFTALMOLOGICOS GENERALES - SER-OFT-005 - CONSULTA OFTALMOLOGICA DE CONTROL',
                            'doctor' => '',
                            'fecha' => '',
                            'hora' => '',
                            'sede_departamento' => '',
                            'id_sede' => null,
                            'afiliacion' => '',
                            'estado_agenda' => 'ATENDIDO',
                            'visita_id' => null,
                        ],
                    ],
                ],
                'requires_dynamic_fixture' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 200,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['success', 'error'],
                'required_json_paths_auth' => ['procedimiento_proyectado', 'billing', 'errores'],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'status_only',
                'post_check_v2_auth' => [
                    'path' => '/v2/api/billing/insertar_billing_main.php',
                    'method' => 'POST',
                    'expect_status' => 400,
                    'body_format' => 'json',
                    'required_json_paths' => ['success', 'error'],
                ],
                'notes' => 'Guest mode validates v2 auth requirement on insertar billing.',
                'notes_auth' => 'Authenticated insert expects structured success response and payload validation behavior.',
            ],
            [
                'id' => 'billing_eliminar_factura',
                'method' => 'POST',
                'legacy_path' => '/informes/api/eliminar-factura',
                'v2_path' => '/v2/informes/api/eliminar-factura',
                'body_format' => 'form',
                'body' => [
                    'form_id' => '{BILLING_FORM_ID}',
                ],
                'requires_dynamic_fixture' => true,
                'destructive' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['success', 'error'],
                'required_json_paths_auth' => ['success', 'message'],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates v2 auth requirement on delete endpoint.',
                'notes_auth' => 'Destructive test: run only with --allow-destructive to validate delete flow.',
            ],
        ],
        'pacientes' => [
            [
                'id' => 'pacientes_datatable',
                'method' => 'POST',
                'legacy_path' => '/pacientes/datatable',
                'v2_path' => '/v2/pacientes/datatable',
                'body_format' => 'form',
                'body' => [
                    'draw' => 1,
                    'start' => 0,
                    'length' => 10,
                    'search' => ['value' => ''],
                ],
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['draw', 'recordsTotal', 'recordsFiltered', 'data', 'error'],
                'required_json_paths_auth' => ['draw', 'recordsTotal', 'recordsFiltered', 'data'],
                'compare_mode' => 'full',
                'notes' => 'Guest parity: both legacy and v2 return 401. Use --cookie=PHPSESSID=... to validate authenticated parity.',
                'notes_auth' => 'Authenticated parity expects both legacy and v2 to return 200 with DataTable payload.',
            ],
            [
                'id' => 'pacientes_detalles',
                'method' => 'GET',
                'legacy_path' => '/pacientes/detalles?hc_number={HC_NUMBER}',
                'v2_path' => '/v2/pacientes/detalles?hc_number={HC_NUMBER}',
                'expect_status' => 401,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['data.patientData.hc_number', 'data.timelineItems'],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Legacy redirects unauthenticated users; v2 returns JSON 401 for API clients. With cookie, validate full patient context.',
                'notes_auth' => 'Run with --hc-number using an existing patient to validate authenticated patient context.',
            ],
            [
                'id' => 'pacientes_flujo',
                'method' => 'GET',
                'legacy_path' => '/pacientes/flujo?hc_number={HC_NUMBER}',
                'v2_path' => '/v2/pacientes/flujo?hc_number={HC_NUMBER}',
                'expect_status' => 401,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['data', 'meta.count'],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Legacy flujo is protected HTML; v2 flujo is protected JSON API.',
                'notes_auth' => 'Authenticated parity validates status parity and v2 flujo payload.',
            ],
            [
                'id' => 'pacientes_detalles_update',
                'method' => 'POST',
                'legacy_path' => '/pacientes/detalles?hc_number={HC_NUMBER}',
                'v2_path' => '/v2/pacientes/detalles?hc_number={HC_NUMBER}',
                'body_format' => 'form',
                'body' => [
                    'actualizar_paciente' => '1',
                ],
                'expect_status' => 401,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 302,
                'expect_v2_status_auth' => 302,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'status_only',
                'body_from_v2_json_auth' => [
                    'path' => '/v2/pacientes/detalles?hc_number={HC_NUMBER}',
                    'method' => 'GET',
                    'expect_status' => 200,
                    'required' => true,
                    'fields' => [
                        'fname' => 'data.patientData.fname',
                        'mname' => 'data.patientData.mname',
                        'lname' => 'data.patientData.lname',
                        'lname2' => 'data.patientData.lname2',
                        'afiliacion' => 'data.patientData.afiliacion',
                        'fecha_nacimiento' => 'data.patientData.fecha_nacimiento',
                        'sexo' => 'data.patientData.sexo',
                        'celular' => 'data.patientData.celular',
                    ],
                ],
                'post_check_v2_auth' => [
                    'path' => '/v2/pacientes/detalles?hc_number={HC_NUMBER}',
                    'method' => 'GET',
                    'expect_status' => 200,
                    'required_json_paths' => ['data.patientData.hc_number'],
                    'assert_json_equals' => [
                        'data.patientData.fname' => '@body.fname',
                        'data.patientData.lname' => '@body.lname',
                        'data.patientData.afiliacion' => '@body.afiliacion',
                        'data.patientData.celular' => '@body.celular',
                    ],
                ],
                'notes' => 'Guest mode validates v2 unauthorized behavior for write endpoint.',
                'notes_auth' => 'Authenticated write parity checks status (302) and validates persisted patient fields in v2.',
            ],
            [
                'id' => 'pacientes_detalles_solicitud',
                'method' => 'GET',
                'legacy_path' => '/pacientes/detalles/solicitud?hc_number={HC_NUMBER}',
                'v2_path' => '/v2/pacientes/detalles/solicitud?hc_number={HC_NUMBER}',
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 422,
                'expect_v2_status_auth' => 422,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['error'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for detalle solicitud endpoint.',
                'notes_auth' => 'Authenticated mode validates 422 contract when required form_id is missing.',
            ],
            [
                'id' => 'pacientes_detalles_section',
                'method' => 'GET',
                'legacy_path' => '/pacientes/detalles/section?hc_number={HC_NUMBER}&section=solicitudes&limit=5',
                'v2_path' => '/v2/pacientes/detalles/section?hc_number={HC_NUMBER}&section=solicitudes&limit=5',
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['data', 'meta.section', 'meta.summary', 'meta.total_rows', 'meta.filters'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for paciente 360 section endpoint.',
                'notes_auth' => 'Authenticated mode validates section payload contract for paciente 360.',
            ],
        ],
        'solicitudes' => [
            [
                'id' => 'solicitudes_kanban_data',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/kanban-data',
                'v2_path' => '/v2/solicitudes/kanban-data',
                'body_format' => 'form',
                'body' => [
                    'fechaTexto' => '',
                ],
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [
                    'data',
                    'options.afiliaciones',
                    'options.doctores',
                    'options.crm.etapas',
                    'options.metrics.sla',
                ],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for solicitudes kanban endpoint.',
                'notes_auth' => 'Authenticated mode validates status parity and base kanban payload shape in v2.',
            ],
            [
                'id' => 'solicitudes_dashboard_data',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/dashboard-data',
                'v2_path' => '/v2/solicitudes/dashboard-data',
                'expect_status' => 401,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [
                    'data.volumen.por_mes.labels',
                    'data.volumen.por_procedimiento.labels',
                    'data.kanban.total',
                    'data.cobertura.status.sent',
                    'filters.date_from',
                    'filters.date_to',
                ],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates dashboard-data auth requirement under /v2.',
                'notes_auth' => 'Authenticated mode validates status parity and dashboard payload structure in v2.',
            ],
            [
                'id' => 'solicitudes_turnero_data',
                'method' => 'GET',
                'legacy_path' => '/solicitudes/turnero-data',
                'v2_path' => '/v2/solicitudes/turnero-data',
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['data'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for turnero endpoint.',
                'notes_auth' => 'Authenticated mode validates turnero payload status parity in v2.',
            ],
        ],
        'solicitudes_writes' => [
            [
                'id' => 'solicitudes_actualizar_estado',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/actualizar-estado',
                'v2_path' => '/v2/solicitudes/actualizar-estado',
                'body_format' => 'json',
                'body' => [
                    'id' => 1,
                    'estado' => 'apto-oftalmologo',
                    'completado' => true,
                    'force' => true,
                ],
                'body_from_v2_json_auth' => [
                    'path' => '/v2/solicitudes/kanban-data',
                    'method' => 'POST',
                    'body_format' => 'form',
                    'body' => [
                        'fechaTexto' => '',
                    ],
                    'expect_status' => 200,
                    'fields' => [
                        'id' => 'data.0.id',
                        'form_id' => 'data.0.form_id',
                    ],
                ],
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => [
                    'success',
                    'estado',
                    'checklist',
                    'checklist_progress.total',
                ],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'destructive' => true,
                'notes' => 'Write endpoint requires auth in guest mode.',
                'notes_auth' => 'Destructive write: updates checklist/estado. Use --allow-destructive.',
            ],
            [
                'id' => 'solicitudes_api_estado_post',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/api/estado',
                'v2_path' => '/v2/solicitudes/api/estado',
                'body_format' => 'json',
                'body' => [
                    'id' => 1,
                ],
                'body_from_v2_json_auth' => [
                    'path' => '/v2/solicitudes/kanban-data',
                    'method' => 'POST',
                    'body_format' => 'form',
                    'body' => [
                        'fechaTexto' => '',
                    ],
                    'expect_status' => 200,
                    'fields' => [
                        'id' => 'data.0.id',
                        'estado' => 'data.0.estado',
                    ],
                ],
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['message'],
                'required_json_paths_auth' => ['success'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for /solicitudes/api/estado.',
                'notes_auth' => 'Authenticated write validates status parity and success flag.',
            ],
        ],
        'solicitudes_crm_writes' => [
            [
                'id' => 'solicitudes_crm_guardar_detalles',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/{SOLICITUD_ID}/crm',
                'v2_path' => '/v2/solicitudes/{SOLICITUD_ID}/crm',
                'body_format' => 'json',
                'body' => [
                    'pipeline_stage' => 'Recibido',
                    'fuente' => 'smoke-v2',
                    'custom_fields' => [],
                ],
                'requires_dynamic_solicitud_fixture' => true,
                'destructive' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['success', 'data.detalle'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for CRM detalles write.',
                'notes_auth' => 'Destructive write: guarda detalles CRM base en solicitudes.',
            ],
            [
                'id' => 'solicitudes_crm_agregar_nota',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/{SOLICITUD_ID}/crm/notas',
                'v2_path' => '/v2/solicitudes/{SOLICITUD_ID}/crm/notas',
                'body_format' => 'json',
                'body' => [
                    'nota' => 'Smoke v2 CRM nota',
                ],
                'requires_dynamic_solicitud_fixture' => true,
                'destructive' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['success', 'data.notas'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for CRM nota write.',
                'notes_auth' => 'Destructive write: registra una nota CRM en la solicitud.',
            ],
            [
                'id' => 'solicitudes_crm_guardar_tarea',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/{SOLICITUD_ID}/crm/tareas',
                'v2_path' => '/v2/solicitudes/{SOLICITUD_ID}/crm/tareas',
                'body_format' => 'json',
                'body' => [
                    'titulo' => 'Smoke tarea v2',
                    'descripcion' => 'Validacion smoke CRM writes',
                ],
                'requires_dynamic_solicitud_fixture' => true,
                'destructive' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['success', 'data.tareas'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for CRM tarea write.',
                'notes_auth' => 'Destructive write: registra tarea CRM en la solicitud.',
            ],
            [
                'id' => 'solicitudes_crm_registrar_bloqueo',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/{SOLICITUD_ID}/crm/bloqueo',
                'v2_path' => '/v2/solicitudes/{SOLICITUD_ID}/crm/bloqueo',
                'body_format' => 'json',
                'body' => [
                    'fecha_inicio' => '2026-02-22 10:00:00',
                    'duracion_minutos' => 30,
                    'motivo' => 'Smoke bloqueo v2',
                    'sala' => 'SMOKE',
                ],
                'requires_dynamic_solicitud_fixture' => true,
                'destructive' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['success', 'data.bloqueos_agenda'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'v2_only',
                'notes' => 'Guest mode validates auth requirement for CRM bloqueo write.',
                'notes_auth' => 'Destructive write: registra bloqueo de agenda CRM en la solicitud. Legacy puede fallar por drift de esquema; se valida v2-only.',
            ],
            [
                'id' => 'solicitudes_crm_subir_adjunto',
                'method' => 'POST',
                'legacy_path' => '/solicitudes/{SOLICITUD_ID}/crm/adjuntos',
                'v2_path' => '/v2/solicitudes/{SOLICITUD_ID}/crm/adjuntos',
                'body_format' => 'multipart',
                'body' => [
                    'descripcion' => 'Smoke adjunto v2',
                    'archivo' => [
                        '__file' => [
                            'name' => 'smoke-solicitud-adjunto.txt',
                            'type' => 'text/plain',
                            'content' => 'Smoke adjunto solicitudes v2',
                        ],
                    ],
                ],
                'requires_dynamic_solicitud_fixture' => true,
                'destructive' => true,
                'expect_status' => 401,
                'expect_legacy_status' => 401,
                'expect_v2_status' => 401,
                'expect_legacy_status_auth' => 200,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['error'],
                'required_json_paths_auth' => ['success', 'data.adjuntos'],
                'compare_mode' => 'status_only',
                'compare_mode_auth' => 'status_only',
                'notes' => 'Guest mode validates auth requirement for CRM adjuntos write.',
                'notes_auth' => 'Destructive write: sube adjunto CRM en la solicitud.',
            ],
        ],
        'auth' => [
            [
                'id' => 'auth_logout_unified',
                'method' => 'GET',
                'legacy_path' => '/auth/logout',
                'v2_path' => '/v2/auth/logout',
                'expect_status' => 200,
                'expect_legacy_status' => 302,
                'expect_v2_status' => 200,
                'expect_legacy_status_auth' => 302,
                'expect_v2_status_auth' => 200,
                'required_json_paths' => ['success', 'message'],
                'required_json_paths_auth' => ['success', 'message'],
                'compare_mode' => 'v2_only',
                'compare_mode_auth' => 'v2_only',
                'destructive' => true,
                'notes' => 'Unified logout test is destructive because it invalidates active sessions. Use --allow-destructive.',
                'notes_auth' => 'Unified logout destroys legacy PHPSESSID and Laravel session/cookies in one flow.',
            ],
            [
                'id' => 'auth_migration_status',
                'method' => 'GET',
                'legacy_path' => '/auth/login',
                'v2_path' => '/v2/auth/migration-status',
                'expect_status' => 200,
                'required_json_paths' => ['module', 'status', 'ready', 'checks', 'message'],
                'compare_mode' => 'v2_only',
            ],
        ],
    ],
];
