CREATE TABLE IF NOT EXISTS farmacia_recetas_conciliacion (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    receta_id VARCHAR(50) NOT NULL,
    pedido_id VARCHAR(50) DEFAULT NULL,
    cedula_paciente VARCHAR(20) DEFAULT NULL,
    paciente VARCHAR(255) DEFAULT NULL,
    fecha_recetaCREATE TABLE IF NOT EXISTS farmacia_recetas_conciliacion (
                                                                             id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                                                                             receta_id VARCHAR(50) NOT NULL,
    pedido_id VARCHAR(50) DEFAULT NULL,
    cedula_paciente VARCHAR(20) DEFAULT NULL,
    paciente VARCHAR(255) DEFAULT NULL,
    fecha_receta DATE DEFAULT NULL,
    producto_receta_id VARCHAR(50) DEFAULT NULL,
    codigo_producto_receta VARCHAR(100) DEFAULT NULL,
    producto_receta VARCHAR(255) DEFAULT NULL,
    factura_id VARCHAR(50) DEFAULT NULL,
    detalle_factura_id VARCHAR(50) DEFAULT NULL,
    fecha_factura DATE DEFAULT NULL,
    fecha_facturacion DATETIME DEFAULT NULL,
    departamento_factura VARCHAR(255) DEFAULT NULL,
    cedula_cliente_factura VARCHAR(20) DEFAULT NULL,
    producto_factura_id VARCHAR(50) DEFAULT NULL,
    codigo_producto_factura VARCHAR(100) DEFAULT NULL,
    producto_factura VARCHAR(255) DEFAULT NULL,
    cantidad_facturada DECIMAL(14,4) DEFAULT NULL,
    precio_unitario_facturado DECIMAL(14,4) DEFAULT NULL,
    descuento_total_linea DECIMAL(14,4) DEFAULT NULL,
    descuento_bos_linea DECIMAL(14,4) DEFAULT NULL,
    monto_linea_neto DECIMAL(14,4) DEFAULT NULL,
    monto_linea_unitario_neto DECIMAL(14,4) DEFAULT NULL,
    diff_dias INT DEFAULT NULL,
    tipo_match VARCHAR(30) NOT NULL DEFAULT 'sin_match',
    total_farmacia DECIMAL(14,4) DEFAULT NULL,
    source_from DATE DEFAULT NULL,
    source_to DATE DEFAULT NULL,
    raw_payload JSON DEFAULT NULL,
    matched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_farmacia_recetas_conciliacion_receta (receta_id),
    KEY idx_farmacia_recetas_conciliacion_fecha_receta (fecha_receta),
    KEY idx_farmacia_recetas_conciliacion_tipo_match (tipo_match),
    KEY idx_farmacia_recetas_conciliacion_pedido (pedido_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    DROP VIEW IF EXISTS vw_farmacia_recetas_conciliadas;

    CREATE VIEW vw_farmacia_recetas_conciliadas AS
    SELECT
    ri.id,
    ri.form_id,
    ri.id_ui AS receta_id_ui,
    ri.estado_receta,
    ri.producto,
    ri.vias,
    ri.unidad,
    ri.pauta,
    ri.dosis,
    ri.cantidad,
    ri.total_farmacia,
    ri.observaciones,
    ri.created_at,
    ri.updated_at AS receta_updated_at,
    frc.receta_id AS conciliacion_receta_id,
    frc.pedido_id,
    frc.cedula_paciente,
    frc.paciente,
    frc.fecha_receta,
    frc.producto_receta_id,
    frc.codigo_producto_receta,
    frc.producto_receta,
    frc.factura_id,
    frc.detalle_factura_id,
    frc.fecha_factura,
    frc.fecha_facturacion,
    frc.departamento_factura,
    frc.cedula_cliente_factura,
    frc.producto_factura_id,
    frc.codigo_producto_factura,
    frc.producto_factura,
    frc.cantidad_facturada,
    frc.precio_unitario_facturado,
    frc.descuento_total_linea,
    frc.descuento_bos_linea,
    frc.monto_linea_neto,
    frc.monto_linea_unitario_neto,
    frc.diff_dias,
    frc.tipo_match,
    frc.source_from,
    frc.source_to,
    frc.matched_at,
    frc.updated_at AS conciliacion_updated_at
    FROM recetas_items ri
    LEFT JOIN farmacia_recetas_conciliacion frc
                                                            ON CONVERT(ri.id_ui USING utf8mb4) COLLATE utf8mb4_unicode_ci = frc.receta_id COLLATE utf8mb4_unicode_ci;
    DATE DEFAULT NULL,
    producto_receta_id VARCHAR(50) DEFAULT NULL,
    codigo_producto_receta VARCHAR(100) DEFAULT NULL,
    producto_receta VARCHAR(255) DEFAULT NULL,
    factura_id VARCHAR(50) DEFAULT NULL,
    detalle_factura_id VARCHAR(50) DEFAULT NULL,
    fecha_factura DATE DEFAULT NULL,
    fecha_facturacion DATETIME DEFAULT NULL,
    departamento_factura VARCHAR(255) DEFAULT NULL,
    cedula_cliente_factura VARCHAR(20) DEFAULT NULL,
    producto_factura_id VARCHAR(50) DEFAULT NULL,
    codigo_producto_factura VARCHAR(100) DEFAULT NULL,
    producto_factura VARCHAR(255) DEFAULT NULL,
    cantidad_facturada DECIMAL(14,4) DEFAULT NULL,
    precio_unitario_facturado DECIMAL(14,4) DEFAULT NULL,
    descuento_total_linea DECIMAL(14,4) DEFAULT NULL,
    descuento_bos_linea DECIMAL(14,4) DEFAULT NULL,
    monto_linea_neto DECIMAL(14,4) DEFAULT NULL,
    monto_linea_unitario_neto DECIMAL(14,4) DEFAULT NULL,
    diff_dias INT DEFAULT NULL,
    tipo_match VARCHAR(30) NOT NULL DEFAULT 'sin_match',
    total_farmacia DECIMAL(14,4) DEFAULT NULL,
    source_from DATE DEFAULT NULL,
    source_to DATE DEFAULT NULL,
    raw_payload JSON DEFAULT NULL,
    matched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_farmacia_recetas_conciliacion_receta (receta_id),
    KEY idx_farmacia_recetas_conciliacion_fecha_receta (fecha_receta),
    KEY idx_farmacia_recetas_conciliacion_tipo_match (tipo_match),
    KEY idx_farmacia_recetas_conciliacion_pedido (pedido_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP VIEW IF EXISTS vw_farmacia_recetas_conciliadas;

CREATE VIEW vw_farmacia_recetas_conciliadas AS
SELECT
    ri.id,
    ri.form_id,
    ri.id_ui AS receta_id_ui,
    ri.estado_receta,
    ri.producto,
    ri.vias,
    ri.unidad,
    ri.pauta,
    ri.dosis,
    ri.cantidad,
    ri.total_farmacia,
    ri.observaciones,
    ri.created_at,
    ri.updated_at AS receta_updated_at,
    frc.receta_id AS conciliacion_receta_id,
    frc.pedido_id,
    frc.cedula_paciente,
    frc.paciente,
    frc.fecha_receta,
    frc.producto_receta_id,
    frc.codigo_producto_receta,
    frc.producto_receta,
    frc.factura_id,
    frc.detalle_factura_id,
    frc.fecha_factura,
    frc.fecha_facturacion,
    frc.departamento_factura,
    frc.cedula_cliente_factura,
    frc.producto_factura_id,
    frc.codigo_producto_factura,
    frc.producto_factura,
    frc.cantidad_facturada,
    frc.precio_unitario_facturado,
    frc.descuento_total_linea,
    frc.descuento_bos_linea,
    frc.monto_linea_neto,
    frc.monto_linea_unitario_neto,
    frc.diff_dias,
    frc.tipo_match,
    frc.source_from,
    frc.source_to,
    frc.matched_at,
    frc.updated_at AS conciliacion_updated_at
FROM recetas_items ri
LEFT JOIN farmacia_recetas_conciliacion frc
    ON CONVERT(ri.id_ui USING utf8mb4) COLLATE utf8mb4_unicode_ci = frc.receta_id COLLATE utf8mb4_unicode_ci;
