CREATE TABLE IF NOT EXISTS billing_facturacion_real (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    dedupe_key CHAR(32) NOT NULL,
    form_id VARCHAR(50) NOT NULL,
    procedimiento VARCHAR(255) DEFAULT NULL,
    realizado_por VARCHAR(255) DEFAULT NULL,
    afiliacion VARCHAR(255) DEFAULT NULL,
    paciente VARCHAR(255) DEFAULT NULL,
    cliente VARCHAR(255) DEFAULT NULL,
    fecha_agenda DATETIME DEFAULT NULL,
    fecha_facturacion DATETIME DEFAULT NULL,
    fecha_atencion DATETIME DEFAULT NULL,
    numero_factura VARCHAR(50) DEFAULT NULL,
    factura_id VARCHAR(50) DEFAULT NULL,
    formas_pago VARCHAR(255) DEFAULT NULL,
    codigo_nota VARCHAR(50) DEFAULT NULL,
    monto_honorario DECIMAL(14,4) DEFAULT NULL,
    monto_facturado DECIMAL(14,4) DEFAULT NULL,
    area VARCHAR(255) DEFAULT NULL,
    estado VARCHAR(100) DEFAULT NULL,
    source_month VARCHAR(7) DEFAULT NULL,
    raw_payload JSON DEFAULT NULL,
    scraped_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_billing_facturacion_real_dedupe (dedupe_key),
    UNIQUE KEY uq_billing_facturacion_real_form_id (form_id),
    KEY idx_billing_facturacion_real_factura (factura_id),
    KEY idx_billing_facturacion_real_fecha_facturacion (fecha_facturacion),
    KEY idx_billing_facturacion_real_month (source_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
